services:
  # Backend service
  - type: web
    name: pawsitive-care-backend
    plan: free
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "10000"

  # Frontend service
  - type: web
    name: pawsitive-care-frontend
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: VITE_API_URL
        value: https://pawsitive-care-backend.onrender.com
      - key: NODE_ENV
        value: production
