services:
  # Backend service
  - type: web
    name: pawsitive-care-backend
    plan: free
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3

  # Frontend service
  - type: web
    name: pawsitive-care-frontend
    plan: free
    env: node
    buildCommand: |
      cd frontend
      npm install
      npm run build
    startCommand: |
      cd frontend
      npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
