services:
  # Backend service
  - type: web
    name: pawsitive-care-backend
    plan: free
    env: python
    buildCommand: |
      pip install -r backend/requirements.txt
    startCommand: |
      uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.3

  # Frontend service
  - type: web
    name: pawsitive-care-frontend
    plan: free
    env: node
    buildCommand: |
      cd frontend
      rm -rf node_modules package-lock.json
      npm cache clean --force
      npm install --legacy-peer-deps
      npm install --save-dev @types/node@20.11.19 @types/react@18.2.55 @types/react-dom@18.2.19 @types/react-router-dom@5.3.3
      npm install --save-dev typescript@5.3.3
      npm run build
    startCommand: |
      cd frontend
      npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 20.11.1
      - key: VITE_API_URL
        value: https://pawsitive-care-backend.onrender.com
      - key: NODE_ENV
        value: production
      - key: TSC_COMPILE_ON_ERROR
        value: "true"
